# Generated by Django 5.2.3 on 2025-06-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_appointment_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='jet_ski_type',
            field=models.CharField(choices=[('GTR 230', 'GTR 230 - High Performance'), ('GTX 300', 'GTX 300 - Convenient')], default='GTR 230', max_length=20),
        ),
    ]
