# Generated by Django 5.2.3 on 2025-06-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_skibuddy_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skibuddy',
            name='user_picture',
            field=models.ImageField(default='buddy_images/default.jpg', upload_to='buddy_images/'),
        ),
    ]
