# Generated by Django 5.2.3 on 2025-06-24 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rental',
            name='jet_ski_image',
            field=models.ImageField(blank=True, null=True, upload_to='jetski_photos/'),
        ),
    ]
