# Generated by Django 5.2.3 on 2025-06-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_photo_uploaded_at_rental_jet_ski_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='JetSki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='jetski_photos/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
