# Generated by Django 5.2.3 on 2025-06-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_alter_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
