# Generated by Django 5.2.3 on 2025-06-26 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_rental_promo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('is_available', models.BooleanField(default=True)),
                ('vehicle_type', models.CharField(choices=[('jet_ski', 'Jet Ski'), ('boat', 'Boat')], default='jet_ski', max_length=20)),
                ('horsepower', models.PositiveIntegerField(default=300)),
                ('rider_capacity', models.PositiveIntegerField(default=3)),
                ('top_speed_mph', models.PositiveIntegerField(default=65)),
                ('fuel_capacity_gal', models.DecimalField(decimal_places=2, default=18.5, max_digits=5)),
                ('storage_capacity_gal', models.DecimalField(decimal_places=2, default=42.5, max_digits=5)),
                ('weight_capacity_lb', models.PositiveIntegerField(default=600)),
                ('has_brake_reverse', models.BooleanField(default=True, verbose_name='Brake & Reverse')),
                ('has_audio', models.BooleanField(default=False, verbose_name='Premium Sound System')),
                ('has_display', models.BooleanField(default=True, verbose_name='Touch Display')),
            ],
        ),
        migrations.DeleteModel(
            name='JetSki',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('affiliate', 'Affiliate')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
