# Generated by Django 5.2.3 on 2025-07-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_waiveragreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='skibuddy',
            name='rate_per_hour',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Rate charged per hour in USD', max_digits=6),
        ),
    ]
