# Generated by Django 5.2.3 on 2025-07-14 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0016_skibuddy_rate_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('checkin', 'Check-In'), ('checkout', 'Check-Out')], default='checkin', max_length=10),
        ),
        migrations.AddField(
            model_name='photo',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rentals.rental'),
        ),
        migrations.AddField(
            model_name='rental',
            name='checkin_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='checkout_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rental_rate',
            field=models.DecimalField(decimal_places=2, default=150.0, help_text='Rate charged per hour in USD', max_digits=6),
        ),
    ]
