# Generated by Django 5.2.3 on 2025-07-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0017_photo_photo_type_photo_rental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='pickup_address',
            field=models.CharField(blank=True, help_text='Full address for GPS/Google Maps', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pickup_location_name',
            field=models.CharField(blank=True, help_text='e.g. Dock 7 – Clearwater Beach', max_length=100, null=True),
        ),
    ]
