# Generated by Django 5.2.3 on 2025-07-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0019_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skibuddy',
            name='user_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_profiles/'),
        ),
    ]
