# Generated by Django 5.2.3 on 2025-07-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0020_remove_skibuddy_user_picture_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='jet_ski_image',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='jet_ski_type',
        ),
        migrations.AddField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.vehicle'),
        ),
    ]
